### ISSUE TITLE
Inplace Error when training gan

### ISSUE THREAD

**Issue by otori-bird** [ZhenyueQin/Implementation-MolGAN-PyTorch#3]
Traceback (most recent call last):
  File "main_gan.py", line 65, in <module>
    main(config)
  File "main_gan.py", line 58, in main
    solver.train_and_validate()
  File "/home/disk2/zhongzipeng/MicroDesign/Implementation-MolGAN-PyTorch/solver_gan.py", line 218, in train_and_validate
    self.train_or_valid(epoch_i=i, train_val_test='train')
  File "/home/disk2/zhongzipeng/MicroDesign/Implementation-MolGAN-PyTorch/solver_gan.py", line 379, in train_or_valid
    train_step_V.backward()
  File "/home/disk2/zhongzipeng/anaconda3/envs/Molgan/lib/python3.6/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/disk2/zhongzipeng/anaconda3/envs/Molgan/lib/python3.6/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [512, 45]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

_______________________________________________________________

In my opinion, it's caused by the backward of the generator loss, but i don't know how to fix it. could you help me?

**Comment by bird8693** [comment]
@ZhenyueQin  I have the same problem!

**Comment by kfzyqin** [comment]
Hi, 

Thanks for using this repository and reporting the error. 

However, there is no error when I run the code. I think the error is caused by the package version inconsistencies. I state my python environment as follows: 
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.2                       gpu_0  
_tflow_select             2.1.0                       gpu    anaconda
absl-py                   0.8.0                    pypi_0    pypi
aiohttp                   3.6.2                    pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aioredis                  1.3.1                    pypi_0    pypi
ase                       3.19.0                   pypi_0    pypi
asn1crypto                0.24.0                py37_1003    conda-forge
astor                     0.8.0                    pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.1.0                   pypi_0    pypi
auto-yolo                 0.1                       dev_0    <develop>
backcall                  0.1.0                    py37_0  
beautifulsoup4            4.8.0                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.1.0                      py_0  
blessings                 1.7                      pypi_0    pypi
boto3                     1.9.221                  pypi_0    pypi
botocore                  1.12.221                 pypi_0    pypi
bottleneck                1.3.1            py37hdd07704_0  
brokenaxes                0.2                      pypi_0    pypi
bs4                       0.0.1                    pypi_0    pypi
bunch                     1.0.1                      py_1    conda-forge
bz2file                   0.98                     pypi_0    pypi
bzip2                     1.0.8                h516909a_1    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2020.7.22                     0    anaconda
cachetools                3.1.1                    pypi_0    pypi
cairo                     1.14.12              h8948797_3  
certifi                   2020.6.20                py37_0    anaconda
cffi                      1.12.3           py37h2e261b9_0  
chainer                   7.4.0                    pypi_0    pypi
chainer-chemistry         0.7.0                    pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
chumpy                    0.70                     pypi_0    pypi
click                     7.0                      pypi_0    pypi
clify                     0.2                       dev_0    <develop>
cloudpickle               1.2.1                    pypi_0    pypi
colorama                  0.4.1                    pypi_0    pypi
colorful                  0.5.4                    pypi_0    pypi
commentjson               0.9.0                    pypi_0    pypi
configparser              5.0.0                    pypi_0    pypi
contextlib2               0.5.5                    pypi_0    pypi
cryptography              2.7              py37h72c5cf5_0    conda-forge
cssselect                 1.1.0                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
cudnn                     7.6.5                cuda10.1_0  
cupti                     10.1.168                      0  
cycler                    0.10.0                   py37_0  
cymem                     2.0.2            py37he1b5a44_0    fastai
cython                    0.29.13          py37he1b5a44_0    conda-forge
cython-blis               0.2.4            py37h516909a_1    fastai
dataclasses               0.6                        py_0    fastai
dbus                      1.13.6               h746ee38_0  
decorator                 4.4.0                    pypi_0    pypi
defusedxml                0.6.0                      py_0  
demjson                   2.2.4                    pypi_0    pypi
dgl                       0.4.3post2               py37_0    dglteam
dgl-cuda10.1              0.4.3post2               py37_0    dglteam
dill                      0.3.0                    pypi_0    pypi
dm-sonnet                 1.34                     pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docutils                  0.15.2                   py37_0    conda-forge
dominate                  2.4.0                    pypi_0    pypi
dopamine-rl               2.0.5                    pypi_0    pypi
dps                       0.1                       dev_0    <develop>
easydict                  1.9                        py_0    conda-forge
emailer                   0.1.0                    pypi_0    pypi
en-core-web-sm            2.1.0                    pypi_0    pypi
entrypoints               0.3                      py37_0  
expat                     2.2.6                he6710b0_0  
fastai                    1.0.60                        1    fastai
fastprogress              0.2.2                      py_0    fastai
ffmpeg                    4.0.2                ha0c5888_2    conda-forge
fftw                      3.3.8           nompi_h7f3a6c3_1109    conda-forge
filelock                  3.0.12                     py_0    anaconda
flake8                    3.7.9                    py37_0  
flask                     1.1.1                    pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freeglut                  3.0.0             hf484d3e_1005    conda-forge
freetype                  2.9.1                h8a8886c_1  
freetype-py               2.2.0                    pypi_0    pypi
future                    0.17.1                   pypi_0    pypi
galario                   1.2.1           py37hf484d3e_1001    conda-forge
gast                      0.2.2                      py_0    conda-forge
geos                      3.7.1                he6710b0_0  
gevent                    1.4.0                    pypi_0    pypi
gin-config                0.2.1                    pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.9                    pypi_0    pypi
glib                      2.56.2               hd408876_0  
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
google                    3.0.0                    pypi_0    pypi
google-api-core           1.22.3                   pypi_0    pypi
google-api-python-client  1.7.11                   pypi_0    pypi
google-auth               1.22.0                   pypi_0    pypi
google-auth-httplib2      0.0.3                    pypi_0    pypi
google-pasta              0.1.7                      py_0    anaconda
googleapis-common-protos  1.6.0                    pypi_0    pypi
googledrivedownloader     0.4                      pypi_0    pypi
gpustat                   0.6.0                    pypi_0    pypi
gputil                    1.4.0                    pypi_0    pypi
gpytorch                  1.2.0                    pypi_0    pypi
graphite2                 1.3.13            hf484d3e_1000    conda-forge
greenlet                  0.4.15                   pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
gunicorn                  19.9.0                   pypi_0    pypi
gym                       0.14.0                   pypi_0    pypi
gym-recording             0.0.1                     dev_0    <develop>
h5py                      2.10.0                   pypi_0    pypi
harfbuzz                  1.9.0             he243708_1001    conda-forge
hdf5                      1.10.2               hc401514_3    conda-forge
hiredis                   1.1.0                    pypi_0    pypi
httplib2                  0.13.1                   pypi_0    pypi
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      pypi_0    pypi
igraph                    0.7.1             h2166141_1005    conda-forge
imageio                   2.5.0                    py37_0  
importlib-metadata        0.20                     pypi_0    pypi
importlib_metadata        1.5.0                    py37_0  
inflect                   4.1.0                    py37_0  
intel-openmp              2019.4                      243  
ipykernel                 5.1.4            py37h39e3cac_0  
ipython                   7.12.0           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
iso8601                   0.1.12                   pypi_0    pypi
isodate                   0.6.0                    pypi_0    pypi
itsdangerous              1.1.0                    pypi_0    pypi
jaraco.itertools          5.0.0                      py_0  
jasper                    2.0.14               h07fcdf6_1  
jedi                      0.16.0                   py37_0  
jinja2                    2.10.1                   pypi_0    pypi
jmespath                  0.9.4                    pypi_0    pypi
joblib                    0.13.2                   py37_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.2                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.3                    py37_0  
keras-applications        1.0.8                      py_0  
keras-preprocessing       1.1.0                      py_1  
kfac                      0.2.0                    pypi_0    pypi
kiwisolver                1.1.0            py37he6710b0_0  
lark-parser               0.7.8                    pypi_0    pypi
libboost                  1.67.0               h46d08c1_4  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0             hf484d3e_1000    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libopencv                 3.4.2                hb342d67_1  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.10.1               hd408876_0  
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
llvmlite                  0.31.0                   pypi_0    pypi
lmdb                      1.0.0                    pypi_0    pypi
loguru                    0.3.2                    pypi_0    pypi
manopth                   0.0.1                    pypi_0    pypi
markdown                  3.1.1                      py_0    conda-forge
markupsafe                1.1.1            py37h7b6447c_0  
matplotlib                3.1.1                    pypi_0    pypi
matplotlib-base           3.1.3            py37hef1b27d_0  
mccabe                    0.6.1                    py37_1  
mesh-tensorflow           0.0.5                    pypi_0    pypi
metric-learn              0.3.0                    pypi_0    pypi
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.2.0            py37h23d657b_0    anaconda
mkl_random                1.0.2            py37hd81dba3_0  
mock                      3.0.5                    py37_0    conda-forge
monty                     4.0.0                    pypi_0    pypi
more-itertools            7.2.0                    pypi_0    pypi
mpmath                    1.1.0                    pypi_0    pypi
msgpack                   1.0.0                    pypi_0    pypi
msgpack-numpy             0.4.4.3                  pypi_0    pypi
multidict                 4.7.6                    pypi_0    pypi
multiset                  2.1.1                    pypi_0    pypi
munch                     2.3.2                    pypi_0    pypi
murmurhash                1.0.2            py37he6710b0_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  5.0.4                      py_0  
ncurses                   6.1                  he6710b0_1  
nettle                    3.3                           0    conda-forge
networkx                  2.3                      pypi_0    pypi
ninja                     1.9.0            py37hfd86e86_0  
nltk                      3.4.5                    pypi_0    pypi
notebook                  6.0.3                    py37_0  
numba                     0.48.0                   pypi_0    pypi
numexpr                   2.7.1            py37h423224d_0  
numpy                     1.17.1                   pypi_0    pypi
numpy-base                1.16.4           py37hde5b4d6_0  
nvidia-ml-py3             7.352.0                  pypi_0    pypi
oauth2client              4.1.3                    pypi_0    pypi
observations              0.1.4                    pypi_0    pypi
ogb                       1.2.0                    pypi_0    pypi
olefile                   0.46                     py37_0  
openbabel                 2.4.1                    py37_6    openbabel
opencensus                0.7.10                   pypi_0    pypi
opencensus-context        0.1.1                    pypi_0    pypi
opencv                    3.4.2            py37h6fd60c2_1  
opencv-python             4.1.1.26                 pypi_0    pypi
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1h               h7b6447c_0    anaconda
opt_einsum                3.1.0                      py_0  
orderedattrdict           1.5.1                    pypi_0    pypi
packaging                 19.1                     pypi_0    pypi
palettable                3.3.0                    pypi_0    pypi
pandas                    0.25.1           py37he6710b0_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.6.0                      py_0  
pathtools                 0.1.2                    pypi_0    pypi
patsy                     0.5.1                    py37_0  
pbr                       5.4.5                    pypi_0    pypi
pcre                      8.43                 he6710b0_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    5.0.0                    pypi_0    pypi
pip                       19.2.3                   pypi_0    pypi
pixman                    0.38.0            h516909a_1003    conda-forge
plac                      0.9.6                    py37_0  
plotly                    4.11.0                   pypi_0    pypi
pluggy                    0.12.0                   pypi_0    pypi
plyfile                   0.7.2                    pypi_0    pypi
preshed                   2.0.1            py37he6710b0_0  
pretrainedmodels          0.7.4                    pypi_0    pypi
progress                  1.5                        py_1    conda-forge
progressbar2              3.43.1                   pypi_0    pypi
prometheus_client         0.7.1                      py_0  
promise                   2.2.1                    pypi_0    pypi
prompt_toolkit            3.0.3                      py_0  
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.6.3                    pypi_0    pypi
ptyprocess                0.6.0                    py37_0  
py                        1.8.0                    pypi_0    pypi
py-boost                  1.67.0           py37h04863e7_4  
py-opencv                 3.4.2            py37hb342d67_1  
py-spy                    0.3.3                    pypi_0    pypi
pyasn1                    0.4.7                    pypi_0    pypi
pyasn1-modules            0.2.6                    pypi_0    pypi
pycairo                   1.18.0          py37h1b9232e_1000    conda-forge
pycocotools               2.0.0           py37h14c3975_1000    conda-forge
pycodestyle               2.5.0                    py37_0  
pycparser                 2.19                     py37_0  
pyemd                     0.5.1           py37hb3f55d8_1000    conda-forge
pyflakes                  2.1.1                    py37_0  
pyglet                    1.5.7                    pypi_0    pypi
pygments                  2.4.2                      py_0    anaconda
pymatgen                  2020.9.14                pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pypng                     0.0.20                   pypi_0    pypi
pyqt                      5.9.2            py37h05f1152_2  
pyrender                  0.1.43                   pypi_0    pypi
pyrsistent                0.15.7           py37h7b6447c_0  
pyskiplist                1.0.0                    pypi_0    pypi
pysmile                   0.2                      pypi_0    pypi
pysmiles                  1.0.0                    pypi_0    pypi
pysocks                   1.7.0                    py37_0    conda-forge
pytest                    5.1.2                    pypi_0    pypi
pytest-env                0.6.2                    pypi_0    pypi
python                    3.7.3                h0371630_0  
python-dateutil           2.8.0                      py_0    conda-forge
python-graphviz           0.12                     pypi_0    pypi
python-igraph             0.7.1.post7      py37h516909a_0    conda-forge
python-louvain            0.13                       py_0    conda-forge
python-slugify            4.0.0                    pypi_0    pypi
python-utils              2.3.0                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
python_http_client        3.1.0                      py_0    conda-forge
pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2019.2                     py_0    conda-forge
pywavelets                1.0.3                    pypi_0    pypi
pyyaml                    5.1.2                    pypi_0    pypi
pyzmq                     18.1.0                   pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.2                      py_0  
qtpy                      1.9.0                      py_0  
ray                       1.0.0                    pypi_0    pypi
rdflib                    4.2.2                    pypi_0    pypi
rdkit                     2020.03.1.0      py37hc20afe1_1    rdkit
readline                  7.0                  h7b6447c_5  
redis                     3.4.1                    pypi_0    pypi
regex                     2020.6.8         py37h8f50634_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
retrying                  1.3.3                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
ruamel                    1.0                      py37_0    conda-forge
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
ruamel.yaml               0.16.5           py37h516909a_0    conda-forge
s3transfer                0.2.1                    pypi_0    pypi
sacremoses                0.0.43             pyh9f0ad1d_0    conda-forge
schnetpack                0.3                      pypi_0    pypi
scikit-image              0.15.0                   pypi_0    pypi
scikit-learn              0.21.3                   pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
seaborn                   0.10.0                     py_0    anaconda
semantic-version          2.8.1                    pypi_0    pypi
send2trash                1.5.0                    py37_0  
sendgrid                  6.0.5                      py_0    conda-forge
sentencepiece             0.1.84                   pypi_0    pypi
sentry-sdk                0.18.0                   pypi_0    pypi
setuptools                41.2.0                   pypi_0    pypi
shapely                   1.6.4            py37h86c5351_0  
shortuuid                 1.0.1                    pypi_0    pypi
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0                     py_0    anaconda
smmap                     3.0.4                    pypi_0    pypi
smpl-pytorch              0.0.7                    pypi_0    pypi
soupsieve                 1.9.3                    pypi_0    pypi
spacy                     2.1.8            py37hc9558a2_0    fastai
spglib                    1.16.0                   pypi_0    pypi
sqlite                    3.28.0               h7b6447c_0  
srsly                     0.1.0            py37he1b5a44_0    fastai
statsmodels               0.10.1                   pypi_0    pypi
submitit                  1.1.1              pyh9f0ad1d_0    conda-forge
subprocess32              3.5.4                    pypi_0    pypi
sympy                     1.4                      pypi_0    pypi
tabulate                  0.8.3                    pypi_0    pypi
templatemail              0.2.0                    pypi_0    pypi
tensor2tensor             1.14.0                   pypi_0    pypi
tensorboard               1.14.0                   py37_0    conda-forge
tensorboard-logger        0.1.0                    pypi_0    pypi
tensorboardx              1.8                        py_0    conda-forge
tensorflow                1.14.0          gpu_py37h74c33d7_0  
tensorflow-base           1.14.0          gpu_py37he45bfe2_0  
tensorflow-datasets       1.2.0                    pypi_0    pypi
tensorflow-estimator      1.14.0                     py_0  
tensorflow-gan            1.0.0.dev0               pypi_0    pypi
tensorflow-gpu            1.14.0                   pypi_0    pypi
tensorflow-metadata       0.14.0                   pypi_0    pypi
tensorflow-probability    0.7.0                    pypi_0    pypi
tensorpack                0.9.8                    pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
text-unidecode            1.3                      pypi_0    pypi
tf-metrics                0.0.1                    pypi_0    pypi
thinc                     7.0.8            py37hc9558a2_0    fastai
tk                        8.6.8                hbc83047_0  
torch                     1.6.0                    pypi_0    pypi
torch-cluster             1.5.3                    pypi_0    pypi
torch-geometric           1.6.1                    pypi_0    pypi
torch-scatter             2.0.4                    pypi_0    pypi
torch-sparse              0.6.1                    pypi_0    pypi
torch-spline-conv         1.2.0                    pypi_0    pypi
torchfile                 0.1.0                      py_0    conda-forge
torchgeometry             0.1.2                    pypi_0    pypi
torchtext                 0.4.0              pyhb384e40_1    pytorch
torchvision               0.4.0                    pypi_0    pypi
torchviz                  0.0.1                    pypi_0    pypi
tornado                   6.0.3            py37h7b6447c_0  
tqdm                      4.35.0                   pypi_0    pypi
traitlets                 4.3.3                    py37_0  
transformers              2.1.1                      py_0    conda-forge
transforms3d              0.3.1                    pypi_0    pypi
trimesh                   3.8.11                   pypi_0    pypi
twisted                   19.7.0                   pypi_0    pypi
typing                    3.6.6                    pypi_0    pypi
typing-extensions         3.6.6                    pypi_0    pypi
typing_extensions         3.7.4.2                    py_0    conda-forge
uncertainties             2.4.4                    pypi_0    pypi
uritemplate               3.0.0                    pypi_0    pypi
urllib3                   1.25.3                   py37_0    conda-forge
visdom                    0.1.8.8                       0    conda-forge
wandb                     0.10.4                   pypi_0    pypi
wasabi                    0.2.2                      py_0    fastai
watchdog                  0.10.3                   pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    py37_1  
websocket-client          0.56.0                   py37_0    conda-forge
werkzeug                  0.15.5                   pypi_0    pypi
wheel                     0.33.6                   pypi_0    pypi
widgetsnbextension        3.5.1                    py37_0  
wordcloud                 1.6.0            py37h516909a_0    conda-forge
wrapt                     1.11.2           py37h7b6447c_0    anaconda
x264                      1!152.20180806       h14c3975_0    conda-forge
xlrd                      1.2.0                    pypi_0    pypi
xlwt                      1.3.0                    py37_0  
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libx11               1.6.8                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                h96e3832_1    anaconda
yarl                      1.6.0                    pypi_0    pypi
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0
